-- ============================================================
-- HitMaster Schema Additions v2.1
-- Paste into Supabase SQL Editor → Run
-- Safe to run on an existing schema — uses IF NOT EXISTS
-- ============================================================

-- ─── APP CONFIG TABLE ────────────────────────────────────────
-- Stores creator-controlled settings: engine weights, nationwide URL,
-- feature flags. Read by the app on startup.
CREATE TABLE IF NOT EXISTS public.app_config (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key         text NOT NULL UNIQUE,
  value       text NOT NULL,
  description text,
  updated_at  timestamptz NOT NULL DEFAULT now(),
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS app_config_key_idx ON public.app_config(key);

-- RLS
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_read_app_config ON public.app_config;
DROP POLICY IF EXISTS allow_all_app_config ON public.app_config;
CREATE POLICY allow_all_app_config ON public.app_config
  FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.app_config TO anon, authenticated;


-- ─── ADAPTIVE TRACKING TABLE ─────────────────────────────────
-- Tracks ZK6 prediction vs actual result for each slate generated.
-- Powers the Adaptive Learning panel in Creator Access.
-- Schema: one row per slate pick, with actual result filled in after draw.
CREATE TABLE IF NOT EXISTS public.adaptive_tracking (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slate_date      date NOT NULL,
  scope           text NOT NULL CHECK (scope IN ('midday','evening','allday')),
  slate_hash      text NOT NULL,
  rank            integer NOT NULL,
  combo           text NOT NULL,           -- e.g. "742"
  combo_set       text NOT NULL,           -- e.g. "{2,4,7}"
  signal_box      real NOT NULL DEFAULT 0, -- BOX percentile score at slate time
  signal_pburst   real NOT NULL DEFAULT 0, -- PBURST percentile score
  signal_co       real NOT NULL DEFAULT 0, -- CO percentile score
  signal_burst    real NOT NULL DEFAULT 0, -- Recency burst score
  energy_score    integer NOT NULL DEFAULT 0,
  mode            text NOT NULL DEFAULT 'balanced',
  -- Filled in after the draw result is known:
  actual_result   text,                    -- e.g. "742" — actual drawn number
  actual_set      text,                    -- e.g. "{2,4,7}"
  hit_box         boolean,                 -- Did the combo_set match actual_set?
  hit_straight    boolean,                 -- Did combo exactly match actual_result?
  -- Which signals were in top quartile (>=75) for this pick
  box_top_quartile    boolean DEFAULT false,
  pburst_top_quartile boolean DEFAULT false,
  co_top_quartile     boolean DEFAULT false,
  burst_top_quartile  boolean DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now(),
  result_at       timestamptz             -- When actual result was recorded
);

CREATE INDEX IF NOT EXISTS adaptive_date_scope_idx 
  ON public.adaptive_tracking(slate_date, scope);
CREATE INDEX IF NOT EXISTS adaptive_hash_idx 
  ON public.adaptive_tracking(slate_hash);
CREATE INDEX IF NOT EXISTS adaptive_hit_box_idx 
  ON public.adaptive_tracking(hit_box) WHERE hit_box IS NOT NULL;

ALTER TABLE public.adaptive_tracking ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_all_adaptive ON public.adaptive_tracking;
CREATE POLICY allow_all_adaptive ON public.adaptive_tracking
  FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.adaptive_tracking TO anon, authenticated;


-- ─── USER SESSIONS TABLE ─────────────────────────────────────
-- Tracks anonymous app sessions. No PII. Used for:
--   - Counting active users (for the "2,400+ players" social proof)
--   - Feature usage analytics  
--   - Subscription tier distribution
CREATE TABLE IF NOT EXISTS public.user_sessions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_token   text NOT NULL UNIQUE, -- Random UUID generated by app on first launch
  tier            text NOT NULL DEFAULT 'free' CHECK (tier IN ('free','pro','plus')),
  platform        text,                 -- 'ios' | 'android' | 'web'
  app_version     text,
  first_seen      timestamptz NOT NULL DEFAULT now(),
  last_seen       timestamptz NOT NULL DEFAULT now(),
  draw_count      integer NOT NULL DEFAULT 0,  -- How many draws this session has checked
  slate_count     integer NOT NULL DEFAULT 0   -- How many slates generated
);

CREATE INDEX IF NOT EXISTS user_sessions_token_idx 
  ON public.user_sessions(session_token);
CREATE INDEX IF NOT EXISTS user_sessions_tier_idx 
  ON public.user_sessions(tier);
CREATE INDEX IF NOT EXISTS user_sessions_last_seen_idx 
  ON public.user_sessions(last_seen DESC);

ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_all_sessions ON public.user_sessions;
CREATE POLICY allow_all_sessions ON public.user_sessions
  FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.user_sessions TO anon, authenticated;


-- ─── SIGNAL HIT RATE VIEW ─────────────────────────────────────
-- Aggregated view used by the Adaptive Learning panel.
-- Shows per-signal hit rates and suggests weight adjustments.
CREATE OR REPLACE VIEW public.v_signal_hit_rates AS
SELECT
  COUNT(*) FILTER (WHERE hit_box IS NOT NULL)         AS total_evaluated,
  COUNT(*) FILTER (WHERE hit_box = true)              AS total_hits,
  ROUND(
    COUNT(*) FILTER (WHERE hit_box = true)::numeric /
    NULLIF(COUNT(*) FILTER (WHERE hit_box IS NOT NULL), 0) * 100, 1
  )                                                    AS box_hit_rate_pct,
  -- Signal hit rates: % of hits where that signal was top-quartile
  ROUND(
    COUNT(*) FILTER (WHERE hit_box = true AND box_top_quartile = true)::numeric /
    NULLIF(COUNT(*) FILTER (WHERE hit_box IS NOT NULL AND box_top_quartile = true), 0) * 100, 1
  )                                                    AS box_signal_hit_rate,
  ROUND(
    COUNT(*) FILTER (WHERE hit_box = true AND pburst_top_quartile = true)::numeric /
    NULLIF(COUNT(*) FILTER (WHERE hit_box IS NOT NULL AND pburst_top_quartile = true), 0) * 100, 1
  )                                                    AS pburst_signal_hit_rate,
  ROUND(
    COUNT(*) FILTER (WHERE hit_box = true AND co_top_quartile = true)::numeric /
    NULLIF(COUNT(*) FILTER (WHERE hit_box IS NOT NULL AND co_top_quartile = true), 0) * 100, 1
  )                                                    AS co_signal_hit_rate,
  ROUND(
    COUNT(*) FILTER (WHERE hit_box = true AND burst_top_quartile = true)::numeric /
    NULLIF(COUNT(*) FILTER (WHERE hit_box IS NOT NULL AND burst_top_quartile = true), 0) * 100, 1
  )                                                    AS burst_signal_hit_rate,
  MIN(slate_date)                                      AS first_date,
  MAX(slate_date)                                      AS last_date,
  COUNT(DISTINCT slate_date)                           AS days_tracked
FROM public.adaptive_tracking;


-- ─── COVERAGE SUMMARY VIEW ───────────────────────────────────
-- Shows which class × scope × horizon combinations have data.
-- Used by the Creator Coverage Matrix screen.
CREATE OR REPLACE VIEW public.v_coverage_summary AS
SELECT
  'box'         AS data_type,
  class_id,
  scope,
  horizon_label,
  COUNT(*)      AS row_count,
  MAX(last_seen) AS latest_seen,
  MAX(updated_at) AS last_updated
FROM public.datasets_box
WHERE deleted_at IS NULL
GROUP BY class_id, scope, horizon_label
UNION ALL
SELECT
  'pair'        AS data_type,
  class_id,
  scope,
  horizon_label,
  COUNT(*)      AS row_count,
  MAX(last_seen) AS latest_seen,
  MAX(updated_at) AS last_updated
FROM public.datasets_pair
WHERE deleted_at IS NULL
GROUP BY class_id, scope, horizon_label
ORDER BY data_type, class_id, scope, horizon_label;


-- ─── IMPORT HEALTH VIEW ──────────────────────────────────────
-- Aggregated import health stats used by the Health Tests panel.
CREATE OR REPLACE VIEW public.v_import_health AS
SELECT
  COUNT(*)                                              AS total_imports,
  COUNT(*) FILTER (WHERE status = 'completed')          AS completed,
  COUNT(*) FILTER (WHERE status = 'failed')             AS failed,
  COUNT(*) FILTER (WHERE status = 'deleted')            AS deleted,
  COUNT(*) FILTER (WHERE status = 'pending')            AS pending,
  SUM(counts) FILTER (WHERE status = 'completed')       AS total_rows_imported,
  MAX(created_at)                                       AS last_import_at,
  MIN(created_at) FILTER (WHERE status = 'failed')      AS last_failure_at
FROM public.imports;


-- ─── UPDATE app_config TRIGGER ───────────────────────────────
-- Auto-updates the updated_at timestamp whenever a config value changes.
CREATE OR REPLACE FUNCTION public.update_app_config_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS app_config_updated_at ON public.app_config;
CREATE TRIGGER app_config_updated_at
  BEFORE UPDATE ON public.app_config
  FOR EACH ROW EXECUTE FUNCTION public.update_app_config_timestamp();


-- ─── SEED DEFAULT CONFIG ──────────────────────────────────────
INSERT INTO public.app_config (key, value, description) VALUES
  ('nationwide_enabled',       'true',
   'Whether Pro users see the nationwide play feature'),
  ('nationwide_url',           'https://www.thelotter.com',
   'The service URL shown to Pro users in the Learn screen'),
  ('nationwide_description',   'Legal lottery concierge — buy tickets in 40+ states from home.',
   'Description text shown alongside the nationwide URL'),
  ('engine_preset',            'balanced',
   'Active weight preset: balanced | conservative | aggressive'),
  ('engine_weights_balanced',  '{"BOX":0.40,"PBURST":0.40,"CO":0.20}',
   'ZK6 balanced weight configuration'),
  ('engine_weights_conservative','{"BOX":0.70,"PBURST":0.20,"CO":0.10}',
   'ZK6 conservative weight configuration'),
  ('engine_weights_aggressive', '{"BOX":0.25,"PBURST":0.45,"CO":0.30}',
   'ZK6 aggressive weight configuration'),
  ('drawing_confidence_on',    'true',
   'Apply Drawing Report Card confidence adjustment to signals'),
  ('burst_signal_on',          'true',
   'Apply Recency Burst Detection bonus signal'),
  ('k6_singles_max',           '4',  'Max singles in K6 slate'),
  ('k6_doubles_max',           '2',  'Max doubles in K6 slate'),
  ('k6_triples_on',            'false', 'Allow triples in K6 slate'),
  ('pair_rep_cap',             '2',  'Max picks sharing same TopPair'),
  ('default_scope',            'midday', 'Default scope on app launch'),
  ('zk6_version',              'v2.1', 'Current ZK6 engine version'),
  ('app_version',              '2.0.0', 'Current app version')
ON CONFLICT (key) DO UPDATE
  SET value = EXCLUDED.value,
      description = EXCLUDED.description;


-- Force PostgREST to reload schema
NOTIFY pgrst, 'reload schema';

-- Confirm
DO $$
BEGIN
  RAISE NOTICE 'Schema additions v2.1 complete.';
  RAISE NOTICE 'New tables: app_config, adaptive_tracking, user_sessions';
  RAISE NOTICE 'New views: v_signal_hit_rates, v_coverage_summary, v_import_health';
END $$;
