// MKT-33 — one-tap day captions sheet.
//
// Renders EVERY caption from today's run into a single PDF and uploads it to
// the public marketing-reels bucket at captions/<YYYYMMDD>.pdf, where the
// Admin → Reels screen offers it as a download. The operator posting from a
// phone gets the whole morning's copy in one file instead of opening eight
// cards to copy eight captions.
//
// "Today's run" uses the SAME semantics as the Reels screen: rows whose
// updated_at falls on today's ET day — NOT reel_date, because the verify reel
// is dated D−1 by design and a reel_date filter would exclude it forever.
//
// Regenerated by every publish (including --captions-only refreshes, which are
// exactly the runs that change captions), so the file tracks the drafts the
// rows actually carry — including operator edits saved before the refresh ran.
// A failure here must never fail a publish: callers wrap it in try/catch and
// the daily run treats the sheet as best-effort.
//
// PDF path mirrors render-handoff-pdf.ts: write HTML, open via file:// (NOT
// setContent — the MKT-10 serif lesson), print with Chromium. Web-safe system
// sans only; no brand fonts, this is an operator sheet, not a public asset.
import { config as loadEnv } from 'dotenv';
import { writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { POSTING_SESSIONS, SCHEDULE_SKIP_ORDER, postingOrder } from '../constants/postingSchedule';

const BUCKET = 'marketing-reels';
const PRUNE_DAYS = 30; // matches publish-reels row/object retention

// The posting schedule rides as PAGE 1 (operator ask, 2026-08-03; redesigned
// same day: ONE page, large type — the sheet answers "what do I post", the
// cover answers "when, in what order", readable at arm's length). Data comes
// from constants/postingSchedule.ts, shared with the Reels screen; the
// reasoning prose stays in assets/marketing/POSTING_SCHEDULE.txt. The
// caption cards below it are SORTED INTO POSTING ORDER and grouped under
// session headers, so the PDF reads top-to-bottom as the operator's day.

/** Operator-facing labels, kept in step with ReelsView's KIND_UI. */
const KIND_LABEL: Record<string, string> = {
  allday_pro: '⚡ All-Day · PRO',
  allday_free: '🎁 All-Day · FREE',
  allday_public: '🌐 All-Day · PUBLIC (cross-post)',
  midday_pro: '🌤 Midday · PRO',
  midday_free: '🌤 Midday · FREE',
  evening_pro: '🌙 Evening · PRO',
  evening_free: '🌙 Evening · FREE',
  verify: '🧾 Verify — Receipts',
  verify_public: '🌐 Verify · PUBLIC (cross-post)',
  verify_midday: '⏱️ Midday · Same-Day Verify',
};

/** Session a kind posts in, for the caption-card group headers. */
function sessionOf(kind: string): { time: string; title: string } | null {
  const s = POSTING_SESSIONS.find(x => x.kinds.includes(kind));
  return s ? { time: s.time, title: s.title } : null;
}

interface Row {
  reel_date: string; kind: string; caption: string; caption_pro: string | null;
  status: string; updated_at: string;
}

function creds(): { url: string; key: string } {
  loadEnv({ path: '.env.backtest' });
  const url = process.env.SUPABASE_URL?.replace(/\/$/, '');
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error('Missing .env.backtest credentials (SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY).');
  return { url, key };
}

const etDay = (iso: string) => new Date(iso).toLocaleDateString('en-CA', { timeZone: 'America/New_York' });

/** Generation clock for the sheet's face, in Eastern time — the operator's
 *  wall clock. Any timestamp a PDF viewer shows from file metadata is UTC,
 *  which reads wrong on a phone at posting time; this one is authoritative.
 *  America/New_York, not a fixed offset, so it tracks EST/EDT correctly. */
const etNow = () =>
  new Date().toLocaleTimeString('en-US', { timeZone: 'America/New_York', hour: 'numeric', minute: '2-digit' });

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function buildHtml(rows: Row[], dayISO: string): string {
  // ── Page 1: the schedule card. One page, large type, times ET. ──────────
  const sessions = POSTING_SESSIONS.map((s) => {
    const reels = s.kinds.length
      ? `<div class="reels">${s.kinds.map((k) => `<span class="reel">${esc(KIND_LABEL[k] ?? `🎬 ${k}`)}</span>`).join('<span class="arrow">→</span>')}</div>`
      : '';
    return `<div class="sess${s.kinds.length ? '' : ' dim'}">
      <div class="t">${esc(s.time)}</div>
      <div class="body">
        <div class="title">${esc(s.title)}</div>
        ${reels}
        ${s.deadline ? `<div class="dl">⏰ ${esc(s.deadline)}</div>` : ''}
        ${s.note ? `<div class="note">${esc(s.note)}</div>` : ''}
      </div>
    </div>`;
  }).join('\n');
  const schedulePage = `<div class="sched">
    <div class="schedhead">
      <h1>POSTING SCHEDULE</h1>
      <div class="sub">all times EASTERN · v1 · canonical prose: assets/marketing/POSTING_SCHEDULE.txt</div>
    </div>
    ${sessions}
    <div class="skip">${esc(SCHEDULE_SKIP_ORDER)}</div>
  </div>`;

  // ── Caption cards, sorted into POSTING ORDER and grouped by session. ────
  const ordered = [...rows].sort((a, b) => postingOrder(a.kind) - postingOrder(b.kind));
  let lastSession = '';
  const cards = ordered.map((r) => {
    const label = KIND_LABEL[r.kind] ?? `🎬 ${r.kind}`;
    const pro = r.caption_pro
      ? `<div class="tag">PRO GROUP DRAFT</div><pre>${esc(r.caption_pro)}</pre>`
      : '';
    const freeTag = r.caption_pro ? '<div class="tag">FREE GROUP DRAFT</div>' : '';
    const sess = sessionOf(r.kind);
    const sessKey = sess ? `${sess.time} — ${sess.title}` : 'Unscheduled';
    const header = sessKey !== lastSession
      ? `<div class="sesshead">🕐 ${esc(sessKey)}</div>`
      : '';
    lastSession = sessKey;
    return `${header}<section>
      <h2>${esc(label)} <span class="meta">· board date ${esc(r.reel_date)} · ${esc(r.status)}</span></h2>
      ${freeTag}<pre>${esc(r.caption)}</pre>${pro}
    </section>`;
  }).join('\n');
  return `<!doctype html><html><head><meta charset="utf-8"><style>
    * { box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #111; margin: 0; padding: 28px 34px; }
    h1 { font-size: 17px; margin: 0 0 2px; letter-spacing: 0.5px; }
    .sub { font-size: 10px; color: #666; margin-bottom: 18px; }
    section { border: 1px solid #ddd; border-radius: 8px; padding: 12px 14px; margin-bottom: 12px; page-break-inside: avoid; }
    h2 { font-size: 12px; margin: 0 0 6px; }
    .meta { font-weight: 400; color: #888; font-size: 10px; }
    .tag { font-size: 8.5px; font-weight: 700; letter-spacing: 1px; color: #7c3aed; margin: 6px 0 2px; }
    pre { font-family: inherit; font-size: 11px; line-height: 1.45; white-space: pre-wrap; margin: 4px 0 0; }
    /* Page 1 — the schedule card. Sized to hold five sessions + footer on one
       Letter page at arm's-length type; do not add prose here, it lives in
       POSTING_SCHEDULE.txt. */
    .sched { page-break-after: always; }
    .schedhead h1 { font-size: 34px; margin: 6px 0 3px; }
    .schedhead .sub { font-size: 13px; margin-bottom: 16px; }
    .sess { display: flex; gap: 20px; padding: 24px 2px; border-bottom: 2px solid #eee; }
    .sess.dim { opacity: 0.5; }
    .sess .t { flex: 0 0 152px; font-size: 31px; font-weight: 800; letter-spacing: -0.5px; }
    .sess .title { font-size: 20px; font-weight: 700; margin-bottom: 7px; }
    .sess .reels { font-size: 17.5px; line-height: 1.65; }
    .sess .reel { font-weight: 600; white-space: nowrap; }
    .sess .arrow { color: #999; margin: 0 9px; }
    .sess .dl { font-size: 16.5px; font-weight: 800; color: #b91c1c; margin-top: 7px; }
    .sess .note { font-size: 13.5px; color: #555; line-height: 1.45; margin-top: 6px; }
    .skip { font-size: 15px; font-weight: 700; margin-top: 20px; padding: 14px 16px; background: #f4f4f5; border-radius: 8px; }
    .sesshead { font-size: 13px; font-weight: 800; letter-spacing: 0.5px; margin: 14px 0 6px; color: #444; }
  </style></head><body>
    ${schedulePage}
    <h1>HITMASTER ZK6 — DAY CAPTIONS</h1>
    <div class="sub">Run day ${esc(dayISO)} · generated ${esc(etNow())} ET · ${rows.length} caption set${rows.length === 1 ? '' : 's'} · internal operator sheet — captions are the lint-gated drafts on the registered rows, in posting order</div>
    ${cards}
  </body></html>`;
}

/** Delete captions/<stamp>.pdf objects older than the retention window. */
async function pruneOldPdfs(url: string, key: string): Promise<void> {
  const list = await fetch(`${url}/storage/v1/object/list/${BUCKET}`, {
    method: 'POST',
    headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ prefix: 'captions/', limit: 200 }),
  });
  if (!list.ok) return; // best-effort
  const objs: { name: string }[] = await list.json();
  const cutoff = new Date(new Date().toLocaleString('en-US', { timeZone: 'America/New_York' }));
  cutoff.setDate(cutoff.getDate() - PRUNE_DAYS);
  const cutStamp = cutoff.toLocaleDateString('en-CA').replace(/-/g, '');
  const stale = objs
    .map((o) => o.name)
    .filter((n) => { const m = n.match(/^(\d{8})\.pdf$/); return m && m[1] < cutStamp; })
    .map((n) => `captions/${n}`);
  if (!stale.length) return;
  await fetch(`${url}/storage/v1/object/${BUCKET}`, {
    method: 'DELETE',
    headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ prefixes: stale }),
  });
}

/**
 * Build + upload the sheet for TODAY's run. Exported for publish-reels.ts;
 * also runnable standalone: npm run reel:captions-pdf.
 */
export async function generateAndUploadCaptionsPdf(dayISO?: string): Promise<void> {
  const { url, key } = creds();
  const res = await fetch(
    `${url}/rest/v1/marketing_reels?status=neq.archived&select=reel_date,kind,caption,caption_pro,status,updated_at&order=kind.asc&limit=50`,
    { headers: { apikey: key, Authorization: `Bearer ${key}` } },
  );
  if (!res.ok) throw new Error(`marketing_reels read → HTTP ${res.status}`);
  const today = dayISO ?? etDay(new Date().toISOString());
  const rows = ((await res.json()) as Row[]).filter((r) => etDay(r.updated_at) === today);
  if (!rows.length) { console.log(`[captions-pdf] no rows updated today (${today}) — nothing to render.`); return; }

  const stamp = today.replace(/-/g, '');
  const htmlPath = join(tmpdir(), `hm_captions_${stamp}.html`);
  const pdfPath = join(tmpdir(), `hm_captions_${stamp}.pdf`);
  writeFileSync(htmlPath, buildHtml(rows, today));

  const { chromium } = await import('playwright'); // lazy — publish imports this module
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage();
    await page.goto(pathToFileURL(htmlPath).href, { waitUntil: 'networkidle' });
    await page.pdf({ path: pdfPath, format: 'Letter', printBackground: true });
  } finally {
    await browser.close();
  }

  const body = new Uint8Array(await import('node:fs').then((fs) => fs.readFileSync(pdfPath)));
  const up = await fetch(`${url}/storage/v1/object/${BUCKET}/captions/${stamp}.pdf`, {
    method: 'POST',
    headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/pdf', 'x-upsert': 'true' },
    body,
  });
  if (!up.ok) throw new Error(`captions pdf upload → HTTP ${up.status}: ${(await up.text()).slice(0, 200)}`);
  console.log(`[captions-pdf] ↑ captions/${stamp}.pdf — ${rows.length} caption set(s), visible on Admin → Reels`);
  await pruneOldPdfs(url, key);
}

// Standalone entry: tsx scripts/render-captions-pdf.ts [--day=YYYY-MM-DD]
// --day regenerates a past run day's sheet (rows must still exist, i.e. inside
// the 30-day retention window). The daily publish never passes it.
if (process.argv[1]?.endsWith('render-captions-pdf.ts')) {
  const day = process.argv.find((a) => a.startsWith('--day='))?.slice(6);
  generateAndUploadCaptionsPdf(day).catch((e) => { console.error('[captions-pdf]', e); process.exit(1); });
}
